[package]
name = "mltalk-client"
version = "0.1.0"
edition = "2021"

[dependencies]
mltalk-core = { path = "../core" }
clap = { version = "4.5.23", features = ["derive"] }
rustyline = "15.0.0"
colored = "2.0"
