[package]
name = "mltalk"
version = "0.1.0"
edition = "2021"

[dependencies]
mltalk-core = { path = "../core" }
clap = { version = "4.5.23", features = ["derive"] }
reqwest = { version = "0.12.10", features = ["blocking"] }
urlencoding = "2.1.3"
rustyline = "15.0.0"
colored = "2.0"
url = "2.5.4"
